choco install googlechrome -y
choco install 7zip -y
choco install everything -y
choco install git -y
choco install nodejs -y
choco install plex -y
choco install postman -y
choco install powertoys -y
choco install spotify -y
choco install steam -y
choco install vscode -y
choco install winfetch -y
choco install x-mouse-button-control -y
choco install dotnet -y
choco install oracle17jdk -y
choco install intellijidea-ultimate -y
choco install internet-download-manager -y